### ISSUE TITLE
Plugin options should be under a single variable

### ISSUE THREAD

**Issue by chris-feist** [pretty-fun-therapy/serverless-plugin-tag-cloud-watch-logs#10]
Its best practice to have the plugin options nested under a plugin-specific variable. Here is an example:

```yaml
custom:
  tagCloudWatchLogs:
    addLambdaTagsOnLogGroups: true
    customTagsFromLambda:
      - "first_tag"
      - "second_tag"
```
