### ISSUE TITLE
Incorrect stackName when specified from provider

### ISSUE THREAD

**Issue by cbm-gplassard** [pretty-fun-therapy/serverless-plugin-tag-cloud-watch-logs#14]
Hello,
we noticed that when we have an overriden stackName specified from the provider.stackName property this plugin doesn't honor it and uses the default one (service + "-" + stage). Which results in an incorrect stackname being used

For example when using custom variables

```
provider:
  name: aws
  stackName: stack-${self:custom.${opt:stage}.suffix}

custom:
  dev:
    suffix: example
  prod:
    suffix: example
```

We have a PR with a fix incoming
