### ISSUE TITLE
Region should be pulled from provider

### ISSUE THREAD

**Issue by chris-feist** [pretty-fun-therapy/serverless-plugin-tag-cloud-watch-logs#5]
It isn't a requirement that region be a command-line option. This plugin should be updated to use the [provider defined region](https://serverless.com/framework/docs/providers/aws/guide/services#serverlessyml) when the command line option is not supplied.

Example `serverless.yml`

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
```
